#!/usr/bin/env python3
"""Deterministic local oracle for AutoFDE's RDF/SPARQL/Tera generation surface.

The production generator is ggen. This renderer exists to validate the exact source,
queries, templates, and generated bytes in environments where the ggen executable is
not mounted. Templates intentionally use the common Tera/Jinja subset.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

from jinja2 import Environment, FileSystemLoader, StrictUndefined
from rdflib import BNode, Graph, Literal, URIRef

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "ggen.toml"


class Row(dict[str, Any]):
    """Dictionary with attribute access, matching Tera row ergonomics."""

    def __getattr__(self, key: str) -> Any:
        try:
            return self[key]
        except KeyError as exc:
            raise AttributeError(key) from exc


def term_value(value: Any) -> Any:
    if value is None:
        return ""
    if isinstance(value, Literal):
        native = value.toPython()
        return native if isinstance(native, (bool, int, float)) else str(native)
    if isinstance(value, (URIRef, BNode)):
        return str(value)
    return value


def query_rows(graph: Graph, query: str) -> list[Row]:
    result = graph.query(query)
    variables = [str(variable) for variable in result.vars]
    rows: list[Row] = []
    for result_row in result:
        rows.append(Row({name: term_value(value) for name, value in zip(variables, result_row)}))
    return rows


def load_config() -> dict[str, Any]:
    with CONFIG.open("rb") as handle:
        return tomllib.load(handle)


def load_graph(config: dict[str, Any]) -> Graph:
    graph = Graph()
    seen: set[Path] = set()
    for relative in [config["ontology"]["source"], *config["ontology"].get("imports", [])]:
        path = (ROOT / relative).resolve()
        if path in seen:
            continue
        graph.parse(path, format="turtle")
        seen.add(path)
    return graph


@dataclass(frozen=True)
class RenderedArtifact:
    rule: str
    output_file: str
    content: bytes

    @property
    def sha256(self) -> str:
        return hashlib.sha256(self.content).hexdigest()


def render_all(graph: Graph, config: dict[str, Any]) -> list[RenderedArtifact]:
    environment = Environment(
        loader=FileSystemLoader(str(ROOT)),
        undefined=StrictUndefined,
        autoescape=False,
        keep_trailing_newline=True,
        trim_blocks=False,
        lstrip_blocks=False,
    )
    environment.globals["sparql"] = lambda query: query_rows(graph, query)

    rendered: list[RenderedArtifact] = []
    for rule in config["generation"]["rules"]:
        query_spec = rule["query"]
        query_text = (
            (ROOT / query_spec["file"]).read_text(encoding="utf-8")
            if "file" in query_spec
            else query_spec["inline"]
        )
        anchor_rows = query_rows(graph, query_text)
        if not anchor_rows and not rule.get("skip_empty", True):
            raise RuntimeError(f"generation rule {rule['name']} has an empty anchor query")
        if not anchor_rows and rule.get("skip_empty", True):
            continue

        template_path = rule["template"]["file"]
        template = environment.get_template(template_path)
        content = template.render(rows=anchor_rows).encode("utf-8")
        rendered.append(
            RenderedArtifact(
                rule=rule["name"],
                output_file=rule["output_file"],
                content=content,
            )
        )
    return rendered


def write_artifacts(artifacts: Iterable[RenderedArtifact], root: Path = ROOT) -> None:
    for artifact in artifacts:
        destination = root / artifact.output_file
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(artifact.content)


def check_artifacts(artifacts: Iterable[RenderedArtifact], root: Path = ROOT) -> list[str]:
    drift: list[str] = []
    for artifact in artifacts:
        destination = root / artifact.output_file
        if not destination.exists() or destination.read_bytes() != artifact.content:
            drift.append(artifact.output_file)
    return drift


def deterministic_receipt(graph: Graph, config: dict[str, Any]) -> dict[str, Any]:
    first = render_all(graph, config)
    second = render_all(graph, config)
    first_map = {item.output_file: item.content for item in first}
    second_map = {item.output_file: item.content for item in second}
    if first_map != second_map:
        raise RuntimeError("reference generation is nondeterministic")
    return {
        "schema": "autofde.reference-generation-receipt.v1",
        "artifacts": [
            {
                "rule": artifact.rule,
                "path": artifact.output_file,
                "sha256": artifact.sha256,
                "bytes": len(artifact.content),
            }
            for artifact in first
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--receipt", action="store_true")
    args = parser.parse_args()

    config = load_config()
    graph = load_graph(config)
    artifacts = render_all(graph, config)

    if args.write:
        write_artifacts(artifacts)
    elif args.check:
        drift = check_artifacts(artifacts)
        if drift:
            print("REFUSED:GENERATED_DRIFT " + ",".join(drift))
            return 2
    else:
        print(json.dumps(deterministic_receipt(graph, config), indent=2, sort_keys=True))

    for artifact in artifacts:
        print(f"GENERATED {artifact.output_file} sha256={artifact.sha256} bytes={len(artifact.content)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
